### ISSUE TITLE
How can I convert my simple json to netcdf format?

### ISSUE THREAD

**Issue by spacelover1** [samharrison7/json2netcdf#2]
Thanks for sharing this repo,
I need to convert my json files to netcdf format.
So my json file is a bunch of  `{"field1": "", "field2": "", "field3": "", "field4": ""}`. 
I gave my json file as input to the code but the input file is about 26MB but the nc file is 330B !  So I think my json format is not compatible with the code, is it possible to change the code so that it would be compatible with this form of json?

**Comment by samharrison7** [comment]
Hi @spacelover1,

Have you given the [json2netcdf-compact.py](https://github.com/samharrison7/json2netcdf/blob/master/json2netcdf-compact.py) script a go? See the very final section of the README. Make sure dimensions are specified with the dimensions key and the variable names that use those dimensions are append with [dim]. Using the `-v` flag when running the script might help as it'll show you what variables are being parsed. Let me know how you get on.

FYI I'm going to get rid of the original json2netcdf.py script as the syntax is too verbose.

Cheers,
Sam

**Comment by spacelover1** [comment]
Hi Sam,
I don't know how to pass my input file to `json2netcdf-compact.py`.
` json2netcdf-compact.py: error: the following arguments are required: input, output`.

Best,

**Comment by samharrison7** [comment]
This should do the trick:

```
json2netcdf-compact.py input_file.json output_file.nc
```
where `input_file.json` is your JSON file and `output_file.nc` is the new NetCDF file to create.

I'll get around to documenting it properly some day...

**Comment by spacelover1** [comment]
Ok so I could run `json2netcdf-compact.py` using your sample JSON file. 
I'm not sure how to specify `x_dim` or `y_dim` for my case.
This is how my data looks like:

![example](https://user-images.githubusercontent.com/17666134/80733081-77022680-8b22-11ea-83e9-9952e29f0395.PNG)

**Comment by samharrison7** [comment]
I'm not sure how you want your data to look in the NetCDF file as it's not really compatible with NetCDF in that format. If you want each of those objects in the list to be groups then they need names. This would work:

```json
{
    "group1": {"userId": 111111, "productId": 1000000, "eventName": 4, "timestamp": 100000000},
    "group2": {"userId": 111111, "productId": 1000000, "eventName": 2, "timestamp": 100000000},
    "group3": {"userId": 111111, "productId": 1000000, "eventName": 4, "timestamp": 100000000},
    "group4": {"userId": 111111, "productId": 1000000, "eventName": 4, "timestamp": 100000000},
    "group5": {"userId": 111111, "productId": 1000000, "eventName": 4, "timestamp": 100000000}
}
```

This gives the following NetCDF file:

```
netcdf test {

group: group1 {
  variables:
        int64 userId ;
        int64 productId ;
        int64 eventName ;
        int64 timestamp ;
  data:

   userId = 111111 ;

   productId = 1000000 ;

   eventName = 4 ;

   timestamp = 100000000 ;
  } // group group1

group: group2 {
  variables:
        int64 userId ;
        int64 productId ;
        int64 eventName ;
        int64 timestamp ;
  data:

   userId = 111111 ;

   productId = 1000000 ;

   eventName = 2 ;

   timestamp = 100000000 ;
  } // group group2

group: group3 {
  variables:
        int64 userId ;
        int64 productId ;
        int64 eventName ;
        int64 timestamp ;
  data:

   userId = 111111 ;

   productId = 1000000 ;

   eventName = 4 ;

   timestamp = 100000000 ;
  } // group group3

group: group4 {
  variables:
        int64 userId ;
        int64 productId ;
        int64 eventName ;
        int64 timestamp ;
  data:

   userId = 111111 ;

   productId = 1000000 ;

   eventName = 4 ;

   timestamp = 100000000 ;
  } // group group4

group: group5 {
  variables:
        int64 userId ;
        int64 productId ;
        int64 eventName ;
        int64 timestamp ;
  data:

   userId = 111111 ;

   productId = 1000000 ;

   eventName = 4 ;

   timestamp = 100000000 ;
  } // group group5
}
```

If you want that list to be a variable with an array of compound data types then I'm afraid this library won't work as it doesn't deal with compound data types.

**Comment by spacelover1** [comment]
Thank you Sam for the complete explanation, actually I want to feed my data to DSSTNE engine and it needs data to be in NetCDF format, and my data is kinda similar to movielens dataset, as you can see [here ](https://github.com/amzn/amazon-dsstne/blob/master/docs/getting_started/examples.md) they have changed CSV to NetCDF before using data.

So my question is that can I use this script of yours in this case?

**Comment by samharrison7** [comment]
I'm not familiar with DSSTNE so not sure I can answer, but having a quick look at the docs you linked to, I think it'd be easier for you to convert your JSON to CSV and then use the method they use for the movielens dataset, you're data looks closer to the movielens CSV format than it is to the NetCDF format (accordingly to [this page](https://github.com/amzn/amazon-dsstne/blob/master/docs/getting_started/userguide.md), anyway).

This JSON to CSV converter looks like it'll work directly on the JSON you posted above, if you don't want to write a script: https://json-csv.com/.

**Comment by samharrison7** [comment]
Closing this as it's not an issue with the software itself.
